services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Validators
    nowo_sepa_payment.validator.iban_validator:
        class: Nowo\SepaPaymentBundle\Validator\IbanValidator
        public: true

    nowo_sepa_payment.validator.bic_validator:
        class: Nowo\SepaPaymentBundle\Validator\BicValidator
        public: true

    nowo_sepa_payment.validator.credit_card_validator:
        class: Nowo\SepaPaymentBundle\Validator\CreditCardValidator
        public: true

    # Converters
    nowo_sepa_payment.converter.ccc_converter:
        class: Nowo\SepaPaymentBundle\Converter\CccConverter
        arguments:
            - '@nowo_sepa_payment.validator.iban_validator'
        public: true

    # Generators
    nowo_sepa_payment.generator.remesa_generator:
        class: Nowo\SepaPaymentBundle\Generator\RemesaGenerator
        arguments:
            - '@nowo_sepa_payment.validator.iban_validator'
        public: true

    nowo_sepa_payment.generator.direct_debit_generator:
        class: Nowo\SepaPaymentBundle\Generator\DirectDebitGenerator
        arguments:
            - '@nowo_sepa_payment.validator.iban_validator'
        public: true

    nowo_sepa_payment.generator.identifier_generator:
        class: Nowo\SepaPaymentBundle\Generator\IdentifierGenerator
        public: true

    # Parsers
    nowo_sepa_payment.parser.remesa_parser:
        class: Nowo\SepaPaymentBundle\Parser\RemesaParser
        public: true

    # Console Commands
    Nowo\SepaPaymentBundle\Command\ValidateIbanCommand:
        tags: ['console.command']
        arguments:
            $ibanValidator: '@nowo_sepa_payment.validator.iban_validator'

    Nowo\SepaPaymentBundle\Command\ConvertCccCommand:
        tags: ['console.command']
        arguments:
            $cccConverter: '@nowo_sepa_payment.converter.ccc_converter'

    Nowo\SepaPaymentBundle\Command\ValidateCreditCardCommand:
        tags: ['console.command']
        arguments:
            $creditCardValidator: '@nowo_sepa_payment.validator.credit_card_validator'

