services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    Nowo\SepaPaymentBundle\Converter\:
        resource: '../../Converter/*'

    Nowo\SepaPaymentBundle\Parser\:
        resource: '../../Parser/*'

    Nowo\SepaPaymentBundle\Generator\:
        resource: '../../Generator/*'

    Nowo\SepaPaymentBundle\Validator\:
        resource: '../../Validator/*'

    # Services are automatically registered via #[AsAlias] attributes
    # All services are public and can be autowired or retrieved by their aliases

    # Console Commands
    # Commands still need explicit configuration for tags and arguments
    Nowo\SepaPaymentBundle\Command\ValidateIbanCommand:
        tags: ['console.command']
        arguments:
            $ibanValidator: '@nowo_sepa_payment.validator.iban_validator'

    Nowo\SepaPaymentBundle\Command\ConvertCccCommand:
        tags: ['console.command']
        arguments:
            $cccConverter: '@nowo_sepa_payment.converter.ccc_converter'

    Nowo\SepaPaymentBundle\Command\ValidateCreditCardCommand:
        tags: ['console.command']
        arguments:
            $creditCardValidator: '@nowo_sepa_payment.validator.credit_card_validator'

